export const JAVA1 = [
"// A. Sizes + vehicle family",
"enum VehicleType { MOTORCYCLE, CAR, TRUCK }",
"enum SpotSize { SMALL, MEDIUM, LARGE }",
"enum SpotState { FREE, OCCUPIED }",
"enum PaymentStatus { PENDING, SUCCESS, FAILED }",
"",
"abstract class Vehicle {",
"  private final String plate;",
"  private final VehicleType type;",
"  protected Vehicle(String p, VehicleType t) { plate = p; type = t; }",
"  public String getPlate() { return plate; }",
"  public abstract boolean canFitIn(SpotSize s);",
"}",
"class Motorcycle extends Vehicle {",
"  Motorcycle(String p) { super(p, VehicleType.MOTORCYCLE); }",
"  public boolean canFitIn(SpotSize s) { return s == SpotSize.SMALL; }",
"}",
"class Car extends Vehicle {",
"  Car(String p) { super(p, VehicleType.CAR); }",
"  public boolean canFitIn(SpotSize s) { return s != SpotSize.SMALL; }",
"}",
"class Truck extends Vehicle {",
"  Truck(String p) { super(p, VehicleType.TRUCK); }",
"  public boolean canFitIn(SpotSize s) { return s == SpotSize.LARGE; }",
"}",
].join("\n");
