export const JAVA2 = [
"// B. Spot + floor + ticket + factory",
"class ParkingSpot {",
"  private final String id;",
"  private final SpotSize size;",
"  private SpotState state = SpotState.FREE;",
"  private Vehicle vehicle;",
"  ParkingSpot(String id, SpotSize s) { this.id = id; size = s; }",
"  public synchronized boolean assign(Vehicle v) {",
"    if (state == SpotState.OCCUPIED) return false;",
"    vehicle = v; state = SpotState.OCCUPIED; return true;",
"  }",
"  public synchronized void release() { vehicle = null; state = SpotState.FREE; }",
"  public boolean isFree() { return state == SpotState.FREE; }",
"  public SpotSize getSize() { return size; }",
"}",
"",
"class Floor {",
"  private final int level;",
"  private final java.util.List<ParkingSpot> spots;",
"  Floor(int l, java.util.List<ParkingSpot> s) { level = l; spots = s; }",
"  public java.util.Optional<ParkingSpot> findFreeSpot(Vehicle v) {",
"    return spots.stream().filter(ParkingSpot::isFree)",
"      .filter(s -> v.canFitIn(s.getSize())).findFirst();",
"  }",
"}",
"",
"class Ticket {",
"  private final String id;",
"  private final Vehicle vehicle;",
"  private final ParkingSpot spot;",
"  private final long entryTime;",
"  private long exitTime;",
"  Ticket(String id, Vehicle v, ParkingSpot s, long e) {",
"    this.id = id; vehicle = v; spot = s; entryTime = e;",
"  }",
"  public void markExit(long t) { exitTime = t; }",
"  public long duration() { return exitTime - entryTime; }",
"  public ParkingSpot getSpot() { return spot; }",
"}",
].join("\n");
