export const JAVA3 = [
"// C. Fee + pay + lot + gates",
"interface PricingStrategy { double fee(Ticket t); }",
"class HourlyPricing implements PricingStrategy {",
"  private final java.util.Map<SpotSize, Double> rates;",
"  HourlyPricing(java.util.Map<SpotSize, Double> r) { rates = r; }",
"  public double fee(Ticket t) {",
"    long hrs = Math.max(1, (long) Math.ceil(t.duration() / 3600000.0));",
"    return hrs * rates.get(t.getSpot().getSize());",
"  }",
"}",
"interface PaymentStrategy { PaymentStatus pay(double amt); }",
"class CashPayment implements PaymentStrategy {",
"  public PaymentStatus pay(double a) { return PaymentStatus.SUCCESS; }",
"}",
"class CardPayment implements PaymentStrategy {",
"  public PaymentStatus pay(double a) { return PaymentStatus.SUCCESS; }",
"}",
"",
"class ParkingLot {",
"  private static volatile ParkingLot ins;",
"  private final java.util.List<Floor> floors;",
"  private ParkingLot(java.util.List<Floor> f) { floors = f; }",
"  public static ParkingLot get(java.util.List<Floor> f) {",
"    if (ins == null) { synchronized (ParkingLot.class) {",
"      if (ins == null) ins = new ParkingLot(f); } }",
"    return ins;",
"  }",
"  public synchronized java.util.Optional<ParkingSpot> allocate(Vehicle v) {",
"    for (Floor f : floors) {",
"      var s = f.findFreeSpot(v);",
"      if (s.isPresent() && s.get().assign(v)) return s;",
"    }",
"    return java.util.Optional.empty();",
"  }",
"  public void release(ParkingSpot s) { s.release(); }",
"}",
"",
"class EntryGate {",
"  private final ParkingLot lot;",
"  EntryGate(ParkingLot l) { lot = l; }",
"  public java.util.Optional<Ticket> admit(Vehicle v, long now, String id) {",
"    return lot.allocate(v).map(s -> new Ticket(id, v, s, now));",
"  }",
"}",
"class ExitGate {",
"  private final ParkingLot lot; private final PricingStrategy pricing;",
"  ExitGate(ParkingLot l, PricingStrategy p) { lot = l; pricing = p; }",
"  public double checkout(Ticket t, PaymentStrategy pay, long now) {",
"    t.markExit(now);",
"    double fee = pricing.fee(t);",
"    if (pay.pay(fee) == PaymentStatus.SUCCESS) lot.release(t.getSpot());",
"    return fee;",
"  }",
"}",
].join("\n");
