export const SQL = [
"-- 4 tables, normalized, minimal",
"",
"CREATE TABLE floors (",
"  floor_id     INT PRIMARY KEY,",
"  level_number INT NOT NULL",
");",
"",
"CREATE TABLE parking_spots (",
"  spot_id  VARCHAR(20) PRIMARY KEY,",
"  floor_id INT NOT NULL,",
"  size     ENUM('SMALL','MEDIUM','LARGE') NOT NULL,",
"  state    ENUM('FREE','OCCUPIED') NOT NULL DEFAULT 'FREE',",
"  FOREIGN KEY (floor_id) REFERENCES floors(floor_id)",
");",
"CREATE INDEX idx_spot_free_size ON parking_spots(state, size);",
"",
"CREATE TABLE tickets (",
"  ticket_id     VARCHAR(20) PRIMARY KEY,",
"  license_plate VARCHAR(20) NOT NULL,",
"  vehicle_type  ENUM('MOTORCYCLE','CAR','TRUCK') NOT NULL,",
"  spot_id       VARCHAR(20) NOT NULL,",
"  entry_time    TIMESTAMP NOT NULL,",
"  exit_time     TIMESTAMP NULL,",
"  amount        DECIMAL(10,2) NULL,",
"  payment_status ENUM('PENDING','SUCCESS','FAILED') DEFAULT 'PENDING',",
"  FOREIGN KEY (spot_id) REFERENCES parking_spots(spot_id)",
");",
"",
"CREATE TABLE payments (",
"  payment_id VARCHAR(20) PRIMARY KEY,",
"  ticket_id  VARCHAR(20) NOT NULL,",
"  method     ENUM('CASH','CARD','UPI') NOT NULL,",
"  amount     DECIMAL(10,2) NOT NULL,",
"  status     ENUM('SUCCESS','FAILED') NOT NULL,",
"  paid_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,",
"  FOREIGN KEY (ticket_id) REFERENCES tickets(ticket_id)",
");",
].join("\n");

export const UML = [
"┌──────────────────────────────────────────────────────┐",
"│              ParkingLot  (Singleton)                │",
"│  - floors: List<Floor>                              │",
"│  + allocate(Vehicle): Optional<ParkingSpot>         │",
"│  + release(ParkingSpot)                             │",
"└──────────┬───────────────────────────────────────────┘",
"           │ ◆ owns (composition — floors die with lot)",
"           ▼",
"┌──────────────────────┐      ┌────────────────────────┐",
"│  Floor               │ ◆───►│  ParkingSpot           │",
"│  - level: int        │ owns │  - id: String          │",
"│  - spots: List<Spot> │      │  - size: SpotSize      │",
"│  + findFreeSpot()    │      │  - state: SpotState    │",
"└──────────────────────┘      │  + assign(Vehicle)     │",
"                              │  + release()           │",
"                              └──────────┬─────────────┘",
"                                         │ holds 0..1",
"                                         ▼",
"                              ┌────────────────────────┐",
"                              │  Vehicle  (abstract)   │",
"                              │  - plate: String       │",
"                              │  + canFitIn(SpotSize)  │",
"                              └──────┬────┬────┬───────┘",
"                      ┌────────────┘    │    └────────────┐",
"                      ▼                 ▼                 ▼",
"               ┌────────────┐   ┌────────────┐   ┌────────────┐",
"               │ Motorcycle │   │    Car     │   │   Truck    │",
"               │ fits SMALL │   │ fits MED+  │   │ fits LARGE │",
"               └────────────┘   └────────────┘   └────────────┘",
"",
"  EntryGate ──creates──► Ticket ◄──reads── ExitGate",
"  ExitGate ──uses──► «interface» PricingStrategy",
"                       ▲            ├── HourlyPricing",
"                       │            └── FlatRatePricing",
"                       └──uses── «interface» PaymentStrategy",
"                                    ├── CashPayment",
"                                    ├── CardPayment",
"                                    └── UpiPayment",
].join("\n");
