// GRAPH & DP (Part 3) — auto-split from Venkatesh's master sheet.
// 25 unique problems · 0 Easy / 0 Medium / 0 Hard
export const dsaProblems = [
  // ===== GRAPH (4) =====
  {
    id: 1,
    title: "BFS of Graph",
    topic: "Graph",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/breadth-first-search-or-bfs-for-a-graph/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 2,
    title: "DFS of Graph",
    topic: "Graph",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 3,
    title: "Count the Number of Complete Components",
    topic: "Graph",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/count-the-number-of-complete-components/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 4,
    title: "Number of Provinces",
    topic: "Graph",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/number-of-provinces/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== DYNAMIC PROGRAMMING (21) =====
  {
    id: 5,
    title: "Climbing Stairs",
    topic: "Dynamic Programming",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/climbing-stairs/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 6,
    title: "Unique Paths",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/unique-paths/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 7,
    title: "Unique Paths II",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/unique-paths-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 8,
    title: "Minimum Path Sum",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/minimum-path-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 9,
    title: "House Robber",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/house-robber/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 10,
    title: "House Robber II",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/house-robber-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 11,
    title: "Friends Pairing Problem",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/friends-pairing-problem/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 12,
    title: "Decode Ways",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/decode-ways/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 13,
    title: "Coin Change",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/coin-change/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 14,
    title: "Coin Change II",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/coin-change-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 15,
    title: "Fibonacci Number",
    topic: "Dynamic Programming",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/fibonacci-number/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 16,
    title: "Distinct Subsequences",
    topic: "Dynamic Programming",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/distinct-subsequences/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 17,
    title: "Dungeon Game",
    topic: "Dynamic Programming",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/dungeon-game/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 18,
    title: "Burst Balloons",
    topic: "Dynamic Programming",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/burst-balloons/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 19,
    title: "01 Matrix",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/01-matrix/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=ZTAseawuRpc",
  },
  {
    id: 20,
    title: "Sum Root to Leaf Numbers",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sum-root-to-leaf-numbers/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 21,
    title: "Path Sum",
    topic: "Dynamic Programming",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/path-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 22,
    title: "Path Sum II",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/path-sum-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 23,
    title: "Path Sum III",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/path-sum-iii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 24,
    title: "Lowest Common Ancestor of a Binary Tree",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 25,
    title: "Divide Two Integers",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/divide-two-integers/",
    platform: "leetcode",
    videoLink: null,
  },
];

