// BASIC DSA (Part 1) — auto-split from Venkatesh's master sheet.
// 115 unique problems · 0 Easy / 0 Medium / 0 Hard
export const dsaBasicProblems = [
  // ===== ARRAYS (20) =====
  {
    id: 1,
    title: "Trapping Rain Water",
    topic: "Arrays",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/trapping-rain-water/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=6z9hrVpUm6s",
  },
  {
    id: 2,
    title: "Maximum of Absolute Value Expression",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-of-absolute-value-expression/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 3,
    title: "Range Sum Query",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/range-sum-query-immutable/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=EGpZNRtvj2U",
  },
  {
    id: 4,
    title: "Range Sum Query 2D",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/range-sum-query-2d-immutable/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=xB7WBIc-LHQ",
  },
  {
    id: 5,
    title: "Search a 2D Matrix",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/search-a-2d-matrix/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=dAWKp8_GtUc",
  },
  {
    id: 6,
    title: "Max Chunks To Make Sorted",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/max-chunks-to-make-sorted/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=Ekc84QC4oFQ",
  },
  {
    id: 7,
    title: "Spiral Matrix",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/spiral-matrix/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 8,
    title: "Matrix Diagonal Sum",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/matrix-diagonal-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 9,
    title: "Sum of all Submatrices",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/sum-of-all-submatrices-of-a-given-matrix/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 10,
    title: "Next Permutation",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/next-permutation/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=SEMS-0d4X6Q",
  },
  {
    id: 11,
    title: "Sort Colors",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sort-colors/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 12,
    title: "Set Matrix Zeroes",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/set-matrix-zeroes/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 13,
    title: "Maximum Subarray",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-subarray/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 14,
    title: "Maximum Gap",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-gap/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 15,
    title: "Container With Most Water",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/container-with-most-water/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 16,
    title: "Subarray Sum Equals K",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/subarray-sum-equals-k/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 17,
    title: "Array Zero Split and Merge",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/check-whether-an-array-can-be-made-0-by-splitting-and-merging-repeatedly/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 18,
    title: "Concatenation of Array",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/concatenation-of-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 19,
    title: "Partition Array According to Given Pivot",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/partition-array-according-to-given-pivot/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 20,
    title: "Find Pairs in Array Whose Sums Already Exist",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/find-pairs-in-array-whose-sums-already-exist-in-array/",
    platform: "gfg",
    videoLink: null,
  },
  // ===== BINARY SEARCH (10) =====
  {
    id: 21,
    title: "Binary Search",
    topic: "Binary Search",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-search/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=JpeuTaAVBiA",
  },
  {
    id: 22,
    title: "Find First and Last Position of Element",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=6tAmm8JjyDY",
  },
  {
    id: 23,
    title: "Single Element in a Sorted Array",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=Pm-e0N2gxqc",
  },
  {
    id: 24,
    title: "Find Minimum in Rotated Sorted Array",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 25,
    title: "Search in Rotated Sorted Array",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 26,
    title: "Maximum in a Sorted and Rotated Array",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/maximum-element-in-a-sorted-and-rotated-array/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 27,
    title: "Find Peak Element",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-peak-element/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=xga-GTt8WBI",
  },
  {
    id: 28,
    title: "Magnetic Force Between Two Balls",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/magnetic-force-between-two-balls/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 29,
    title: "Sqrt(x)",
    topic: "Binary Search",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/sqrtx/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 30,
    title: "Smallest Good Base",
    topic: "Binary Search",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/smallest-good-base/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== BIT MANIPULATION (8) =====
  {
    id: 31,
    title: "Check K-th Bit",
    topic: "Bit Manipulation",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/check-whether-k-th-bit-set-or-not/",
    platform: "gfg",
    videoLink: "https://www.youtube.com/watch?v=lN9lj83lVK8",
  },
  {
    id: 32,
    title: "Reverse Bits",
    topic: "Bit Manipulation",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/reverse-bits/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=lyj1BpGZ8QI",
  },
  {
    id: 33,
    title: "Sum of Two Integers",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sum-of-two-integers/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 34,
    title: "Swap Two Numbers Using Bitwise",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/swap-two-numbers-without-using-third-variable/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 35,
    title: "Single Number",
    topic: "Bit Manipulation",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/single-number/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=hJIlLxGc424",
  },
  {
    id: 36,
    title: "Single Number II",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/single-number-ii/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=2sGMA4LR8pg",
  },
  {
    id: 37,
    title: "Position of Rightmost Set Bit",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/position-of-rightmost-set-bit/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 38,
    title: "Total Hamming Distance",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/total-hamming-distance/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== MATHS (11) =====
  {
    id: 39,
    title: "Fizz Buzz",
    topic: "Maths",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/fizz-buzz/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 40,
    title: "Find Greatest Common Divisor of Array",
    topic: "Maths",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/find-greatest-common-divisor-of-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 41,
    title: "Number of Common Factors",
    topic: "Maths",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/number-of-common-factors/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 42,
    title: "Four Divisors",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/four-divisors/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 43,
    title: "Largest Number That Divides X and is Co-prime with Y",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/largest-number-that-divides-x-and-is-co-prime-with-y/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 44,
    title: "Number of Open Doors",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/number-of-open-doors/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 45,
    title: "Factorial Trailing Zeroes",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/factorial-trailing-zeroes/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 46,
    title: "Count Trailing Zeros",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/count-trailing-zeroes-factorial-number/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 47,
    title: "Rectangle Area",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/rectangle-area/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 48,
    title: "Check If Array Pairs Are Divisible by k",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/check-if-array-pairs-are-divisible-by-k/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 49,
    title: "Distribute Candies",
    topic: "Maths",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/distribute-candies/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== RECURSION (6) =====
  {
    id: 50,
    title: "Print 1 to n using Recursion",
    topic: "Recursion",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/print-1-to-n-without-using-loops/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 51,
    title: "Print N to 1 without Loop",
    topic: "Recursion",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/print-n-to-1-without-using-loops/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 52,
    title: "Print N to 1 and 1 to N Using Recursion",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/print-n-to-1-and-1-to-n-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 53,
    title: "Factorial",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/factorial-of-a-number-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 54,
    title: "Pow(x, n)",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/powx-n/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 55,
    title: "Valid Palindrome",
    topic: "Recursion",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/valid-palindrome/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== SORTING (8) =====
  {
    id: 56,
    title: "Sort an Array",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sort-an-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 57,
    title: "Merge Sorted Array",
    topic: "Sorting",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/merge-sorted-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 58,
    title: "Quick Sort",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/quick-sort/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 59,
    title: "Count Inversions",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/counting-inversions/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 60,
    title: "Sort Array By Parity",
    topic: "Sorting",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/sort-array-by-parity/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 61,
    title: "Minimum Absolute Difference",
    topic: "Sorting",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/minimum-absolute-difference/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 62,
    title: "K Closest Points to Origin",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/k-closest-points-to-origin/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 63,
    title: "Find K Closest Elements",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-k-closest-elements/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== STRINGS (1) =====
  {
    id: 64,
    title: "Backspace String Compare",
    topic: "Strings",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/backspace-string-compare/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== SLIDING WINDOW (3) =====
  {
    id: 65,
    title: "Longest Substring Without Repeating Characters",
    topic: "Sliding Window",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 66,
    title: "Longest Substring with K Uniques",
    topic: "Sliding Window",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/find-the-longest-substring-with-k-unique-characters-in-a-given-string/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 67,
    title: "Max Sum Subarray of Size K",
    topic: "Sliding Window",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/window-sliding-technique/",
    platform: "gfg",
    videoLink: null,
  },
  // ===== STACKS & QUEUES (11) =====
  {
    id: 68,
    title: "Insert an Element at the Bottom of a Stack",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/insert-an-element-at-the-bottom-of-a-stack/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 69,
    title: "Reverse a Stack",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/reverse-a-stack-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 70,
    title: "Next Greater Element",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/next-greater-element/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 71,
    title: "Previous Greater Element",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/previous-greater-element/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 72,
    title: "Smaller on Left",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/smaller-on-left/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 73,
    title: "Next Smaller Element",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/next-smaller-element/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 74,
    title: "Stock Span Problem",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/the-stock-span-problem/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 75,
    title: "Min Stack",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/min-stack/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 76,
    title: "Evaluate Reverse Polish Notation",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 77,
    title: "Daily Temperatures",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/daily-temperatures/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 78,
    title: "Expression Contains Redundant Bracket",
    topic: "Stacks & Queues",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/expression-contains-redundant-bracket-or-not/",
    platform: "gfg",
    videoLink: null,
  },
  // ===== LINKED LISTS (13) =====
  {
    id: 79,
    title: "Middle of the Linked List",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/middle-of-the-linked-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 80,
    title: "Linked List Cycle",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/linked-list-cycle/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 81,
    title: "Reverse Linked List",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/reverse-linked-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 82,
    title: "Remove Nth Node From End of List",
    topic: "Linked Lists",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 83,
    title: "Palindrome Linked List",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/palindrome-linked-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 84,
    title: "Linked List Cycle II",
    topic: "Linked Lists",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/linked-list-cycle-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 85,
    title: "Intersection of Two Linked Lists",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 86,
    title: "Reverse Linked List II",
    topic: "Linked Lists",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/reverse-linked-list-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 87,
    title: "Sort List",
    topic: "Linked Lists",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sort-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 88,
    title: "Convert Binary Number in a Linked List to Integer",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 89,
    title: "Remove Linked List Elements",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/remove-linked-list-elements/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 90,
    title: "Delete Node in a Linked List",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/delete-node-in-a-linked-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 91,
    title: "Merge Two Sorted Lists",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/merge-two-sorted-lists/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== TREES (17) =====
  {
    id: 92,
    title: "Binary Tree Preorder Traversal",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-tree-preorder-traversal/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 93,
    title: "Binary Tree Inorder Traversal",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 94,
    title: "Binary Tree Postorder Traversal",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-tree-postorder-traversal/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 95,
    title: "Maximum Depth of Binary Tree",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 96,
    title: "Binary Tree Right Side View",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/binary-tree-right-side-view/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 97,
    title: "Insert into a Binary Search Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/insert-into-a-binary-search-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 98,
    title: "Validate Binary Search Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/validate-binary-search-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 99,
    title: "Lowest Common Ancestor of a Binary Search Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 100,
    title: "Search in a Binary Search Tree",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/search-in-a-binary-search-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 101,
    title: "Top View of Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/top-view-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 102,
    title: "Bottom View of Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/bottom-view-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 103,
    title: "Left View of Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/left-view-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 104,
    title: "Right View of Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/right-view-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 105,
    title: "Tree Boundary Traversal",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/boundary-traversal-of-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 106,
    title: "Binary Tree Zigzag Level Order Traversal",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 107,
    title: "Diameter of a Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/diameter-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 108,
    title: "Invert Binary Tree",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/invert-binary-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== GREEDY (5) =====
  {
    id: 109,
    title: "N meetings in one room",
    topic: "Greedy",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/n-meetings-in-one-room/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 110,
    title: "Activity Selection",
    topic: "Greedy",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/activity-selection-problem-greedy-algo-1/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 111,
    title: "Minimum Platforms",
    topic: "Greedy",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/minimum-number-platforms-required-railwaybus-station/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 112,
    title: "Maximize Sum Of Array After K Negations",
    topic: "Greedy",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/maximize-sum-of-array-after-k-negations/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 113,
    title: "Last Stone Weight",
    topic: "Greedy",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/last-stone-weight/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== HEAPS (2) =====
  {
    id: 114,
    title: "Kth Largest Element in a Stream",
    topic: "Heaps",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 115,
    title: "Minimum Cost of Ropes",
    topic: "Heaps",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/connect-n-ropes-minimum-cost/",
    platform: "gfg",
    videoLink: null,
  },
];

// Google Crack Coding Series in Telugu intro video
export const googleSeriesIntro = {
  title: "Google Crack Coding Series in Telugu — Introduction",
  videoLink: "https://www.youtube.com/watch?v=5Qqly4rxqDU",
};

// Weekday names
export const weekDays = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
];
export const examDays = [
  { day: "Saturday", label: "Exam 1", emoji: "📝" },
  { day: "Sunday", label: "Exam 2", emoji: "🏆" },
];

// Difficulty ordered set for filters
export const difficulties = ["Easy", "Medium", "Hard"];
