// DSA Basics - A to Z Problems (from Venkatesh's DSA sheet)
// Each problem: id, title, topic, difficulty, link, platform, videoLink (Google Telugu series where available)
export const dsaBasicProblems = [
  // ===== ARRAYS =====
  {
    id: 1,
    title: "Fizz Buzz",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/fizz-buzz/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 2,
    title: "Concatenation of Array",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/concatenation-of-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 3,
    title: "Merge Sorted Array",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/merge-sorted-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 4,
    title: "Sort Array By Parity",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/sort-array-by-parity/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 5,
    title: "Matrix Diagonal Sum",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/matrix-diagonal-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 6,
    title: "Range Sum Query",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/range-sum-query-immutable/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=EGpZNRtvj2U",
  },
  {
    id: 7,
    title: "Range Sum Query 2D",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/range-sum-query-2d-immutable/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=xB7WBIc-LHQ",
  },
  {
    id: 8,
    title: "Sum of All Submatrices",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/sum-of-all-submatrices-of-a-given-matrix/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 9,
    title: "Maximum Subarray",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-subarray/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 10,
    title: "Two Sum",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/two-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 11,
    title: "3 Sum",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/3sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 12,
    title: "4 Sum",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/4sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 13,
    title: "Container With Most Water",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/container-with-most-water/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 14,
    title: "Find All Pairs With Given Sum",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://practice.geeksforgeeks.org/problems/find-all-pairs-with-a-given-sum/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 15,
    title: "Spiral Matrix",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/spiral-matrix/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 16,
    title: "Search a 2D Matrix",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/search-a-2d-matrix/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=dAWKp8_GtUc",
  },
  {
    id: 17,
    title: "Set Matrix Zeroes",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/set-matrix-zeroes/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 18,
    title: "01 Matrix",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/01-matrix/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=ZTAseawuRpc",
  },
  {
    id: 19,
    title: "Next Permutation",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/next-permutation/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=SEMS-0d4X6Q",
  },
  {
    id: 20,
    title: "Partition Array According to Given Pivot",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/partition-array-according-to-given-pivot/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 21,
    title: "Sort Colors",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sort-colors/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 22,
    title: "Max Chunks To Make Sorted",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/max-chunks-to-make-sorted/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=Ekc84QC4oFQ",
  },
  {
    id: 23,
    title: "Max Chunks To Make Sorted II",
    topic: "Arrays",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/max-chunks-to-make-sorted-ii/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=1IKobiCuHnw",
  },
  {
    id: 24,
    title: "Zero Array Transformation I",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/zero-array-transformation-i/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 25,
    title: "Trapping Rain Water",
    topic: "Arrays",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/trapping-rain-water/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=6z9hrVpUm6s",
  },
  {
    id: 26,
    title: "Maximum Gap",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-gap/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 27,
    title: "Maximum of Absolute Value Expression",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-of-absolute-value-expression/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 28,
    title: "Minimum Number of Bottles Visible",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/minimum-number-of-bottles-visible-when-a-bottle-can-be-enclosed-inside-another-bottle/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 29,
    title: "Find pairs in array whose sums already exist",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/find-pairs-in-array-whose-sums-already-exist-in-array/",
    platform: "gfg",
    videoLink: null,
  },

  // ===== MATHS =====
  {
    id: 30,
    title: "Find Greatest Common Divisor of Array",
    topic: "Maths",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/find-greatest-common-divisor-of-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 31,
    title: "Number of Common Factors",
    topic: "Maths",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/number-of-common-factors/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 32,
    title: "Largest number that divides x and is co-prime with y",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/largest-number-that-divides-x-and-is-co-prime-with-y/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 33,
    title: "Four Divisors",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/four-divisors/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 34,
    title: "Number of Open Doors",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://practice.geeksforgeeks.org/problems/number-of-open-doors/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 35,
    title: "Factorial Trailing Zeroes",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/factorial-trailing-zeroes/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 36,
    title: "Count Trailing Zeroes",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/count-trailing-zeroes-factorial-number/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 37,
    title: "Nth Magical Number",
    topic: "Maths",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/nth-magical-number/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 38,
    title: "Preimage Size of Factorial Zeroes Function",
    topic: "Maths",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/preimage-size-of-factorial-zeroes-function/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 39,
    title: "Smallest Good Base",
    topic: "Maths",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/smallest-good-base/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 40,
    title: "Implement Rand10() Using Rand7()",
    topic: "Maths",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/implement-rand10-using-rand7/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=jpcjJ54EEaw",
  },

  // ===== BIT MANIPULATION =====
  {
    id: 41,
    title: "Check K-th Bit",
    topic: "Bit Manipulation",
    difficulty: "Easy",
    link: "https://practice.geeksforgeeks.org/problems/check-k-th-bit/",
    platform: "gfg",
    videoLink: "https://www.youtube.com/watch?v=lN9lj83lVK8",
  },
  {
    id: 42,
    title: "Reverse Bits",
    topic: "Bit Manipulation",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/reverse-bits/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=lyj1BpGZ8QI",
  },
  {
    id: 43,
    title: "Sum of Two Integers",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sum-of-two-integers/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 44,
    title: "Swap Two Numbers Without Third Variable",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/swap-two-numbers-without-using-third-variable/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 45,
    title: "Single Number",
    topic: "Bit Manipulation",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/single-number/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=hJIlLxGc424",
  },
  {
    id: 46,
    title: "Single Number II",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/single-number-ii/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=2sGMA4LR8pg",
  },
  {
    id: 47,
    title: "Position of Rightmost Set Bit",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/position-of-rightmost-set-bit/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 48,
    title: "Total Hamming Distance",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/total-hamming-distance/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 49,
    title: "Divide Two Integers",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/divide-two-integers/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== SEARCHING =====
  {
    id: 50,
    title: "Binary Search",
    topic: "Searching",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-search/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=JpeuTaAVBiA",
  },
  {
    id: 51,
    title: "Search in Rotated Sorted Array",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 52,
    title: "Find Minimum in Rotated Sorted Array",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 53,
    title: "Maximum in a sorted and rotated array",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/maximum-in-a-sorted-and-rotated-array/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 54,
    title: "Find Peak Element",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-peak-element/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=xga-GTt8WBI",
  },
  {
    id: 55,
    title: "Find First and Last Position of Element",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=6tAmm8JjyDY",
  },
  {
    id: 56,
    title: "Single Element in a Sorted Array",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=Pm-e0N2gxqc",
  },
  {
    id: 57,
    title: "Search a 2D Matrix",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/search-a-2d-matrix/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=dAWKp8_GtUc",
  },
  {
    id: 58,
    title: "Capacity to Ship Packages Within D Days",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 59,
    title: "Magnetic Force Between Two Balls",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/magnetic-force-between-two-balls/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 60,
    title: "Find K Closest Elements",
    topic: "Searching",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-k-closest-elements/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 61,
    title: "Sqrt(x)",
    topic: "Searching",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/sqrtx/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== RECURSION =====
  {
    id: 62,
    title: "Print 1 to N",
    topic: "Recursion",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/print-1-to-n-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 63,
    title: "Print N to 1",
    topic: "Recursion",
    difficulty: "Easy",
    link: "https://practice.geeksforgeeks.org/problems/print-n-to-1-without-loop/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 64,
    title: "Print N to 1 and 1 to N",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/print-n-to-1-and-1-to-n-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 65,
    title: "Factorial",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://practice.geeksforgeeks.org/problems/factorial/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 66,
    title: "Pow(x, n)",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/powx-n/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 67,
    title: "Valid Palindrome",
    topic: "Recursion",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/valid-palindrome/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 68,
    title: "Permutations",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/permutations/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 69,
    title: "Permutations II",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/permutations-ii/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== BACKTRACKING =====
  {
    id: 70,
    title: "N Queens",
    topic: "Backtracking",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/n-queens/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 71,
    title: "Rat in a Maze",
    topic: "Backtracking",
    difficulty: "Hard",
    link: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 72,
    title: "Sudoku Solver",
    topic: "Backtracking",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/sudoku-solver/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 73,
    title: "Palindrome Partitioning",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/palindrome-partitioning/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 74,
    title: "Letter Combinations of a Phone Number",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 75,
    title: "Combination Sum III",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/combination-sum-iii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 76,
    title: "Target Sum",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/target-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 77,
    title: "Letter Case Permutation",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/letter-case-permutation/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 78,
    title: "Gray Code",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/gray-code/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 79,
    title: "Subsets",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/subsets/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== SORTING =====
  {
    id: 80,
    title: "Sort an Array",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sort-an-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 81,
    title: "Quick Sort",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://practice.geeksforgeeks.org/problems/quick-sort/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 82,
    title: "Count Inversions",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://practice.geeksforgeeks.org/problems/count-inversions/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 83,
    title: "Reverse Pairs",
    topic: "Sorting",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/reverse-pairs/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 84,
    title: "Count of Smaller Numbers After Self",
    topic: "Sorting",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 85,
    title: "Sort Colors",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sort-colors/",
    platform: "leetcode",
    videoLink: null,
  },
];

// Google Crack Coding Series in Telugu intro video
export const googleSeriesIntro = {
  title: "Google Crack Coding Series in Telugu — Introduction",
  videoLink: "https://www.youtube.com/watch?v=5Qqly4rxqDU",
};

// Weekday names
export const weekDays = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
];
export const examDays = [
  { day: "Saturday", label: "Exam 1", emoji: "📝" },
  { day: "Sunday", label: "Exam 2", emoji: "🏆" },
];

// Difficulty ordered set for filters
export const difficulties = ["Easy", "Medium", "Hard"];
