// ADVANCED DSA (Part 2) — auto-split from Venkatesh's master sheet.
// 38 unique problems · 0 Easy / 0 Medium / 0 Hard
export const dsaProblems = [
  // ===== MATHS (2) =====
  {
    id: 1,
    title: "Permutation Sequence",
    topic: "Maths",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/permutation-sequence/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 2,
    title: "Max Points on a Line",
    topic: "Maths",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/max-points-on-a-line/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== STRINGS (1) =====
  {
    id: 3,
    title: "Palindrome Pairs",
    topic: "Strings",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/palindrome-pairs/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== SLIDING WINDOW (2) =====
  {
    id: 4,
    title: "Sliding Window Maximum",
    topic: "Sliding Window",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/sliding-window-maximum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 5,
    title: "Minimum Window Substring",
    topic: "Sliding Window",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/minimum-window-substring/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== STACKS & QUEUES (2) =====
  {
    id: 6,
    title: "Largest Rectangle in Histogram",
    topic: "Stacks & Queues",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 7,
    title: "Longest Valid Parentheses",
    topic: "Stacks & Queues",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/longest-valid-parentheses/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== GREEDY (3) =====
  {
    id: 8,
    title: "Candy",
    topic: "Greedy",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/candy/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 9,
    title: "Job Sequencing Problem",
    topic: "Greedy",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/job-sequencing-problem-loss-minimization/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 10,
    title: "Gas Station",
    topic: "Greedy",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/gas-station/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== HEAPS (4) =====
  {
    id: 11,
    title: "Find Median from Data Stream",
    topic: "Heaps",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/find-median-from-data-stream/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 12,
    title: "Find K Pairs with Smallest Sums",
    topic: "Heaps",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 13,
    title: "Merge k Sorted Lists",
    topic: "Heaps",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/merge-k-sorted-lists/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 14,
    title: "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
    topic: "Heaps",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/find-the-kth-smallest-sum-of-a-matrix-with-sorted-rows/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== BACKTRACKING (12) =====
  {
    id: 15,
    title: "N-Queens",
    topic: "Backtracking",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/n-queens/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 16,
    title: "Rat in a Maze",
    topic: "Backtracking",
    difficulty: "Hard",
    link: "https://www.geeksforgeeks.org/rat-in-a-maze-backtracking-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 17,
    title: "Palindrome Partitioning",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/palindrome-partitioning/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 18,
    title: "Sudoku Solver",
    topic: "Backtracking",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/sudoku-solver/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 19,
    title: "Gray Code",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/gray-code/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 20,
    title: "Letter Combinations of a Phone Number",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 21,
    title: "Combination Sum III",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/combination-sum-iii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 22,
    title: "Target Sum",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/target-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 23,
    title: "Letter Case Permutation",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/letter-case-permutation/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 24,
    title: "Subsets",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/subsets/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 25,
    title: "Permutations",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/permutations/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 26,
    title: "Permutations II",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/permutations-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== DIVIDE & CONQUER (3) =====
  {
    id: 27,
    title: "Reverse Pairs",
    topic: "Divide & Conquer",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/reverse-pairs/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 28,
    title: "Count of Smaller Numbers After Self",
    topic: "Divide & Conquer",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 29,
    title: "Kth Largest Element in an Array",
    topic: "Divide & Conquer",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    platform: "leetcode",
    videoLink: null,
  },
  // ===== TRIE (9) =====
  {
    id: 30,
    title: "Implement Trie (Prefix Tree)",
    topic: "Trie",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 31,
    title: "Implement Trie II",
    topic: "Trie",
    difficulty: "Medium",
    link: "https://www.naukri.com/code360/problems/implement-trie-ll_8230840?challengeSlug=coding-interview-prep",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 32,
    title: "Design Add and Search Words Data Structure",
    topic: "Trie",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 33,
    title: "Prefix and Suffix Search",
    topic: "Trie",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/prefix-and-suffix-search/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 34,
    title: "Number of Distinct Substrings in a String",
    topic: "Trie",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/number-of-distinct-substrings-in-a-string/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 35,
    title: "Count Distinct Substrings",
    topic: "Trie",
    difficulty: "Medium",
    link: "https://www.naukri.com/code360/problems/count-distinct-substrings_985286",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 36,
    title: "Maximum XOR of Two Numbers in an Array",
    topic: "Trie",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 37,
    title: "Subarray with XOR less than k",
    topic: "Trie",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/count-subarrays-xor-less-k/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 38,
    title: "Find Shortest Unique Prefix for Every Word",
    topic: "Trie",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/find-shortest-unique-prefix-for-every-word-in-a-given-list/",
    platform: "gfg",
    videoLink: null,
  },
];

